const MockList = [
  {
    id: '1',
    name: 'Alice Smith',
    age: 25,
    bio: 'Loves hiking and photography.',
    distance: '0.5 miles',
    imageUrl: 'https://i.pravatar.cc/250?img=1',
    verified: true,
    tags: ['#hiking', '#photography', '#travel'],
  },
  {
    id: '2',
    name: 'Bob Johnson',
    age: 30,
    bio: 'Coffee enthusiast and coder.',
    distance: '1 mile',
    imageUrl: 'https://i.pravatar.cc/250?img=2',
    verified: false,
    tags: ['#coffee', '#coding', '#music'],
  },
  {
    id: '3',
    name: 'Carol Lee',
    age: 27,
    bio: 'Runner and foodie.',
    distance: '2 miles',
    imageUrl: 'https://i.pravatar.cc/250?img=3',
    verified: true,
    tags: ['#running', '#food', '#anime'],
  },
  {
    id: '4',
    name: 'David Brown',
    age: 22,
    bio: 'Aspiring musician and traveler.',
    distance: '3 miles',
    imageUrl: 'https://i.pravatar.cc/250?img=4',
    verified: true,
    tags: ['#music', '#travel', '#art'],
  },
  {
    id: '5',
    name: 'Eva Green',
    age: 28,
    bio: 'Yoga instructor and wellness coach.',
    distance: '1.5 miles',
    imageUrl: 'https://i.pravatar.cc/250?img=5',
    verified: false,
    tags: ['#yoga', '#wellness', '#health'],
  },
  {
    id: '6',
    name: 'Frank White',
    age: 35,
    bio: 'Tech enthusiast and gamer.',
    distance: '2.5 miles',
    imageUrl: 'https://i.pravatar.cc/250?img=6',
    verified: true,
    tags: ['#tech', '#gaming', '#innovation'],
  },
];

export default MockList;
